### PR TITLE
fix: throw on fractional values with fromdateiso8601

### PR DESCRIPTION
**Pull request by yann-combarnous**
Address issue discussed in #379.

### CODE REVIEW

**Comment by yann-combarnous** [comment]
@eiiches , per our other thread, this should align to current JQ behavior.

**Review by eiiches — APPROVED** [review]
Thank you for fixing this. LGTM :+1:

**Comment by yann-combarnous** [comment]
@eiiches , any chance you could cut a new release in the foreseeable future?

**Comment by eiiches** [comment]
@yann-combarnous Yep, I'll cut a new release by next Monday.

**Comment by eiiches** [comment]
Just released https://github.com/eiiches/jackson-jq/releases/tag/1.2.0. It'll usually take several minutes before maven jar is available for download from the maven central.

**Pull request merged**
