### PR TITLE
add jandex indexes 

### LINKED ISSUE #194: Improved quarkus support: add jandex indexes
As follow up for https://github.com/eiiches/jackson-jq/issues/137, in order to improve the quarkus integration, it would be nice to include a [jandex](https://github.com/smallrye/jandex) index in the generated artifacts.

If this is something that can be acceptable, I can send a PR

### PR DESCRIPTION
**Pull request by lburgazzoli**
Fixes #194

For the jackson-jq module, the jandex plugins indexes the following classes:
```
[INFO] --- jandex-maven-plugin:1.2.2:jandex (make-index) @ jackson-jq ---
[INFO] Indexed net.thisptr.jackson.jq.BuiltinFunction (2 annotations)
[INFO] Indexed net.thisptr.jackson.jq.Function (0 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.filters.AbstractSvFilter (0 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.filters.CsvFilter (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.filters.TsvFilter (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.AbstractAtFormattingFunction (0 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.AbstractKeysFunction (0 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.AbstractMaxByFunction (0 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.AbstractStartsEndsWithFunction (0 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.AbstractTrimStrFunction (0 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.AtBase64Function (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.AtBase64dFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.AtHtmlFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.AtShFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.AtUriFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.BuiltinsFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.ContainsFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.DelPathsFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.EmptyFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.EndsWithFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.EnvFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.ErrorFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.ExplodeFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.FromEntriesFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.FromJsonFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.GetPathFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.GroupByFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.HasFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.ImplodeFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.IndexFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.IndicesFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.InfiniteFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.IsInfiniteFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.IsNanFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.JoinFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.KeysFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.KeysUnsortedFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.LTrimStrFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.LengthFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$AcosFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$AsinFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$AtanFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$CbrtFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$CosFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$CoshFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$Exp10Function (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$Exp2Function (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$ExpFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$Expm1Function (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$FloorFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$Log10Function (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$Log1pFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$Log2Function (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$LogFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$SinFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$SinhFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$SqrtFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$TanFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction$TanhFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MathFunction (0 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MaxByFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.MinByFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.NanFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.NotFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.NowFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.PathFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.PathsFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.RIndexFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.RTrimStrFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.RangeFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.ReverseFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.SetPathFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.SortByFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.SplitFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.StartsWithFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.ToEntriesFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.ToJsonFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.ToNumberFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.ToStringFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.TypeFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.Utf8ByteLengthFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions._MatchImplFunction$1 (0 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions._MatchImplFunction$CaptureObject (2 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions._MatchImplFunction$MatchObject (2 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions._MatchImplFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions._SubImplFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.debug.DebugScopeFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.math.Atan2Function (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.internal.functions.math.PowFunction (1 annotations)
```

For the jackson-jq-extra module, the jandex plugins indexes the following classes:

```
[INFO] --- jandex-maven-plugin:1.2.2:jandex (make-index) @ jackson-jq-extra ---
[INFO] Indexed net.thisptr.jackson.jq.extra.functions.HostnameFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.extra.functions.RandomFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.extra.functions.StrFTimeFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.extra.functions.StrPTimeFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.extra.functions.TimestampFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.extra.functions.UriDecodeFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.extra.functions.UriParseFunction$Result (2 annotations)
[INFO] Indexed net.thisptr.jackson.jq.extra.functions.UriParseFunction (1 annotations)
[INFO] Indexed net.thisptr.jackson.jq.extra.functions.Uuid4Function (1 annotations)
```

### CODE REVIEW

**Comment by eiiches** [comment]
https://github.com/quarkiverse/quarkus-jackson-jq/pull/34/files#r909657106
https://github.com/quarkiverse/quarkus-jackson-jq/pull/34/files#r909663106

**Comment by eiiches** [comment]
https://github.com/eiiches/jackson-jq/pull/197 should be enough to prevent `env/0` from getting loaded by the Quarkus loader. But just to be safe, is it possible to remove net.thisptr.jackson.jq.internal.functions.EnvFunction from the index too?

**Comment by lburgazzoli** [comment]
@eiiches added a filter to exclude env function from indexing

**Comment by eiiches** [comment]
Thanks!

**Comment by eiiches** [comment]
@lburgazzoli Released this in 1.0.0-preview.20220704, but I noticed that the jandex is missing in the final jar. Didn't have time to investigate now, but I'll try to fix it and release a new version later (tomorrow most likely).

**Pull request merged**
