### PR TITLE
Implement normals and finites functions

### PR DESCRIPTION
**Pull request by itchyny**
This PR implements four filtering functions; `isnormal/0`, `normals/0`, `finites/0` and `isfinite/0`.

### CODE REVIEW

**Comment by eiiches** [comment]
Thank you @itchyny !

According to `man 3 isnormal`, `isnormal` also returns false if the value is `too small to be represented in normalized format`.

> Floating point numbers can have special values, such as infinite or NaN.  With the macro fpclassify(x) you can find out what type x is.  The macro takes any floating-point expression as argument.  The result is one of the following values:
> 
> FP_NAN        x is "Not a Number".
> FP_INFINITE   x is either positive infinity or negative infinity.
> FP_ZERO       x is zero.
> FP_SUBNORMAL  x is too small to be represented in normalized format.
> FP_NORMAL     if nothing of the above is correct then it must be a normal floating-point number.
> 
> The other macros provide a short answer to some standard questions.
> 
> isnormal(x)   returns a nonzero value if (fpclassify(x) == FP_NORMAL)

So, isnormal(2 ** (-1022) / 2), assuming the value is represented using IEEE 754 binary64 format, should return `false`, not `true` (see  https://en.wikipedia.org/wiki/Normal_number_(computing) ).

```
$ jq-1.6 -n '2.2250738585072014e-308 / 2 | [isnormal, (. != 0)]'
[ false, true ]
$ bin/jackson-jq -nc '2.2250738585072014e-308 / 2 | [isnormal, (. != 0)]'
[ true, true ]
```

Not sure how we should fix this, but I think the easiest way is to just add `&& v >= Double.MIN_NORMAL` condition to the return statement of IsNormalFunction#test. What do you think?
https://docs.oracle.com/javase/jp/8/docs/api/java/lang/Double.html#MIN_NORMAL

**Comment by eiiches** [comment]
Actually, since v can be negative, the condition should be `&& (v <= -Double.MIN_NORMAL || Double.MIN_NORMAL <= v)`.

**Comment by itchyny** [comment]
Thank you for detail explanation. You're completely correct. I fixed the implementation.

**Comment by eiiches** [comment]
Thanks for the fix. Looks good!

**Pull request merged**
