### PR TITLE
mvn test

### PR DESCRIPTION
**Pull request by gabrieljones**

### CODE REVIEW

**Comment by eiiches** [comment]
Hi @gabrieljones 

I believe `mvn deploy` in the previous step also executes tests, so there's no need to run `mvn test` separately.
https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#a-build-lifecycle-is-made-up-of-phases

Thanks for the PR anyways!

**Comment by gabrieljones** [comment]
~~Hmm... On closer inspection, I don't see a test run here https://github.com/eiiches/jackson-jq/runs/6271297161?check_suite_focus=true~~

Oops nevermind, I see it.

**Comment by gabrieljones** [comment]
There would be a benefit to splitting the dependency download and the test as separate invocations before the deploy step.  This would serve to separate the download noise from the test run, and allow forks to see their test result before the snapshot deploy fails from lacking the settings.xml secrets.

Better yet make the deploy step skip if the settings.xml secret is missing.

**Comment by eiiches** [comment]
> Better yet make the deploy step skip if the settings.xml secret is missing.

Sounds good!

**Pull request closed without merging**
