### PR TITLE
Improved quarkus support: make the jq json node model public #195

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by eiiches** [comment]
Looks good!

**Comment by lburgazzoli** [comment]
@eiiches do you think we can get a new release ?

**Comment by eiiches** [comment]
Yes, I'm going to release a new version in a few days!

**Comment by eiiches** [comment]
Just released 1.0.0-preview.20220705. The jar will be available shortly (there's a delay) from the Maven Central.

**Pull request merged**
