### PR TITLE
feat: Add fromdateiso8601 and todateiso8601

### LINKED ISSUE #321: Support for fromdateiso8601 and todateiso8601
Hi, our organization would like to make use of `fromdateiso8601`, and `todateiso8601`. 
Have a change ready to add to the core list of functions, if they make sense there.

### PR DESCRIPTION
**Pull request by yann-combarnous**
Support for built-in fromdateiso8601 and todateiso8601.

Based on PR #322, taking into account reviewer comments.

Fixes #321 

@eiiches , FYI

### CODE REVIEW

**Review by eiiches — APPROVED** [review]
Thank you for submitting a pull request. LGTM :+1:

**Comment by eiiches** [comment]
Oops, it seems that `fromdateiso8601` shouldn't accept fractional seconds. This has to be fixed before publishing a stable release because the fix to disallow fractional seconds would be a breaking change. Are you willing to submit a fix? @yann-combarnous 

```console
$ jq-1.7.1 fromdateiso8601
"2024-11-25T14:13:48.123Z"
jq: error (at <stdin>:2): date "2024-11-25T14:13:48.123Z" does not match format "%Y-%m-%dT%H:%M:%SZ"

$ java -jar jackson-jq-cli-1.1.1-20241125.141032-1.jar  'fromdateiso8601'
"2024-11-25T14:13:48.123Z"
1732544028
```

**Comment by yann-combarnous** [comment]
> Oops, it seems that `fromdateiso8601` shouldn't accept fractional seconds. This has to be fixed before publishing a stable release because the fix to disallow fractional seconds would be a breaking change. Are you willing to submit a fix? @yann-combarnous
> 
> ```
> $ jq-1.7.1 fromdateiso8601
> "2024-11-25T14:13:48.123Z"
> jq: error (at <stdin>:2): date "2024-11-25T14:13:48.123Z" does not match format "%Y-%m-%dT%H:%M:%SZ"
> 
> $ java -jar jackson-jq-cli-1.1.1-20241125.141032-1.jar  'fromdateiso8601'
> "2024-11-25T14:13:48.123Z"
> 1732544028
> ```

Lack of handling for fractional seconds is raised as a bug, not feature request in JQ, see https://github.com/jqlang/jq/issues/2224 .

So happy to reproduce the bug, if you want me to.

**Comment by yann-combarnous** [comment]
Looks pretty simple to add: from the instant, call getNano and if the value is different than 0, throw exception.

**Pull request merged**
